name: Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            executable: steam-ticket-generator.exe
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            executable: steam-ticket-generator

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build Executable
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: steam-ticket-generator
          path: target/${{ matrix.target }}/release/${{ matrix.executable }}
